CREATE DATABASE LibraryDB;

CREATE TABLE Book (
   Id BIGINT IDENTITY(1,1) PRIMARY KEY,
   Title VARCHAR(100) NOT NULL,
   Summary VARCHAR(2000) NOT NULL,
   Author VARCHAR(100) NOT NULL,
   Isbn VARCHAR(13) NOT NULL,
   CreatedAt DATETIME NOT NULL
);